import type { AppStateSnapshot } from "@/lib/app-types";

export const initialAppState: AppStateSnapshot = {
  role: "owner",
  currentWorkerId: "w1",
  workers: [
    {
      id: "w1",
      name: "Alex Mercer",
      initials: "AM",
      email: "alex.m@example.com",
      reputation: 98,
    },
    {
      id: "w2",
      name: "Sam Chen",
      initials: "SC",
      email: "sam.c@example.com",
      reputation: 96,
    },
  ],
  properties: [
    {
      id: "1235",
      address: "1235 Maple Street",
      city: "Toronto, ON",
      zipCode: "M4J 2T7",
      gateCode: "9482#",
      instructions: "Side gate sticks slightly. Lift while pulling.",
      image:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [
        { id: "w1", name: "Alex Mercer", initials: "AM" },
        { id: "w2", name: "Sam Chen", initials: "SC" },
      ],
      location: { lat: 43.689, lng: -79.329 },
    },
    {
      id: "1002",
      address: "1002 Oakwood Ave",
      city: "Toronto, ON",
      zipCode: "M6E 2W9",
      gateCode: "No gate",
      instructions: "Keypad on the back door. Code is 1122.",
      image:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [{ id: "w1", name: "Alex Mercer", initials: "AM" }],
      location: { lat: 43.69, lng: -79.444 },
    },
    {
      id: "2003",
      address: "45 Pine Street",
      city: "Toronto, ON",
      zipCode: "M3C 1L1",
      gateCode: "1234#",
      instructions:
        "Call if the gate doesn't open. The main door is on the side.",
      image:
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [],
      location: { lat: 43.725, lng: -79.339 },
    },
    {
      id: "2004",
      address: "789 Willow Drive",
      city: "Mississauga, ON",
      zipCode: "L5B 2C9",
      gateCode: "No gate",
      instructions: "Enter through the garage. Code 5566.",
      image:
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [{ id: "w2", name: "Sam Chen", initials: "SC" }],
      location: { lat: 43.589, lng: -79.644 },
    },
    {
      id: "2005",
      address: "321 Cedar Blvd",
      city: "Markham, ON",
      zipCode: "L3R 9W4",
      gateCode: "9988#",
      instructions: "Gate is always open during the day.",
      image:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [{ id: "w1", name: "Alex Mercer", initials: "AM" }],
      location: { lat: 43.856, lng: -79.337 },
    },
    {
      id: "2006",
      address: "555 Birch Rd",
      city: "Richmond Hill, ON",
      zipCode: "L4B 3Z9",
      gateCode: "0000#",
      instructions: "Watch out for the dog in the backyard.",
      image:
        "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [],
      location: { lat: 43.84, lng: -79.39 },
    },
    {
      id: "2007",
      address: "888 Elm Court",
      city: "Vaughan, ON",
      zipCode: "L4K 4R4",
      gateCode: "No gate",
      instructions: "Front door keypad is 4321.",
      image:
        "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=400&h=300",
      whitelistedWorkers: [
        { id: "w1", name: "Alex Mercer", initials: "AM" },
        { id: "w2", name: "Sam Chen", initials: "SC" },
      ],
      location: { lat: 43.794, lng: -79.54 },
    },
  ],
  bounties: [
    {
      id: "bounty-1",
      title: "Lawn Mowing",
      propertyId: "1235",
      ownerLane: "backlog",
      price: 50,
      type: "Fixed Price",
      description:
        "Front and backyard need mowing. Please trim the edges. Grass clippings can be left in the brown bin.",
      isNew: true,
      boosted: false,
      workerStatus: "available",
      acceptedByWorkerId: null,
      timerSecondsRemaining: 7200,
      proofPhotosUploaded: 0,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
    {
      id: "bounty-2",
      title: "Snow Shoveling",
      propertyId: "1002",
      ownerLane: "active",
      price: 35,
      type: "Fixed Price",
      description:
        "Driveway and front walkway need to be cleared of snow. Please salt the steps afterward.",
      isNew: true,
      boosted: false,
      workerStatus: "available",
      acceptedByWorkerId: null,
      timerSecondsRemaining: 7200,
      proofPhotosUploaded: 0,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
    {
      id: "bounty-3",
      title: "Gutter Cleaning",
      propertyId: "2007",
      ownerLane: "in_progress",
      price: 75,
      type: "Fixed Price",
      description:
        "Clean out all leaves and debris from the roof gutters. Must bring your own ladder.",
      isNew: false,
      boosted: false,
      workerStatus: "accepted",
      acceptedByWorkerId: "w1",
      timerSecondsRemaining: 7200,
      proofPhotosUploaded: 0,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
    {
      id: "bounty-4",
      title: "Fence Repair",
      propertyId: "2004",
      ownerLane: "in_progress",
      price: 150,
      type: "Fixed Price",
      description: "Replace two broken wooden panels on the backyard fence.",
      isNew: false,
      boosted: false,
      workerStatus: "accepted",
      acceptedByWorkerId: "w1",
      timerSecondsRemaining: 5400,
      proofPhotosUploaded: 1,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
    {
      id: "bounty-5",
      title: "Plumbing Leak",
      propertyId: "1002",
      ownerLane: "review",
      price: 150,
      type: "Fixed Price",
      description:
        "Investigate and fix a leak under the kitchen sink. Bring basic plumbing tools and replacement fittings.",
      isNew: false,
      boosted: true,
      workerStatus: "pending_approval",
      acceptedByWorkerId: "w2",
      timerSecondsRemaining: 0,
      proofPhotosUploaded: 2,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
    {
      id: "bounty-6",
      title: "Dryer Vent Cleaning",
      propertyId: "2005",
      ownerLane: "pending_payment",
      price: 95,
      type: "Fixed Price",
      description:
        "Completed vent cleaning and lint removal. Waiting for payout processing after owner sign-off.",
      isNew: false,
      boosted: false,
      workerStatus: "pending_approval",
      acceptedByWorkerId: "w2",
      timerSecondsRemaining: 0,
      proofPhotosUploaded: 2,
      tenantBridgeEnabled: true,
      recursiveSchedulingEnabled: false,
    },
  ],
  taskTemplates: [
    {
      id: "lawn",
      label: "Lawn Mowing",
      title: "Lawn Mowing",
      description: "Mow front and back, trim edges. Leave clippings in brown bin.",
      price: 50,
    },
    {
      id: "snow",
      label: "Snow Shoveling",
      title: "Snow Shoveling",
      description:
        "Shovel driveway and walkway to the front door. Apply salt if icy.",
      price: 40,
    },
    {
      id: "gutter",
      label: "Gutter Cleaning",
      title: "Gutter Cleaning",
      description: "Clear leaves from all front and rear gutters. Ladder required.",
      price: 100,
    },
  ],
  ownerFinancials: {
    totalSpentYtd: 1250,
  },
  pendingPayouts: [
    {
      id: "p1",
      workerId: "w1",
      worker: "Alex Mercer",
      email: "alex.m@example.com",
      task: "Lawn Mowing",
      amount: 50,
      property: "1235 Maple St",
    },
    {
      id: "p2",
      workerId: "w2",
      worker: "Sam Chen",
      email: "sam.c@example.com",
      task: "Gutter Cleaning",
      amount: 100,
      property: "1002 Oakwood Ave",
    },
  ],
  taskReminders: [
    {
      id: "r1",
      title: "Winterize Pipes",
      propertiesLabel: "Properties: All",
      badgeLabel: "Due in 5 days",
      badgeVariant: "destructive",
    },
    {
      id: "r2",
      title: "HVAC Filter Change",
      propertiesLabel: "Properties: 1235 Maple",
      badgeLabel: "Due in 14 days",
      badgeVariant: "outline",
    },
  ],
  workerFinancialSummary: {
    totalEarnings: 450,
    pendingPayouts: 125,
    jobsCompleted: 12,
    earningsDeltaText: "+20.1% from last month",
    pendingJobsText: "2 jobs awaiting approval",
    jobsCompletedDeltaText: "+3 this month",
  },
  workerTransactions: [
    {
      id: "tx1",
      bountyId: "bounty-1",
      title: "Lawn Mowing",
      propertyLabel: "1235 Maple St",
      completedOn: "Oct 24, 2023",
      amount: 50,
    },
    {
      id: "tx2",
      bountyId: "bounty-2",
      title: "Snow Shoveling",
      propertyLabel: "482 Oak Ave",
      completedOn: "Feb 12, 2024",
      amount: 35,
    },
    {
      id: "tx3",
      bountyId: "bounty-3",
      title: "Gutter Cleaning",
      propertyLabel: "720 Elm St",
      completedOn: "Jan 05, 2024",
      amount: 75,
    },
  ],
  ui: {
    defaultCity: "Toronto, ON",
    propertyPlaceholderImage:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=400&h=300",
    mapPreviewImage:
      "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=400&h=400",
    noShowTimerSeconds: 7200,
    autoRepostDays: 14,
  },
};
