import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppStateProvider } from "@/lib/app-state";
import { RoleProvider } from "@/components/role-provider";
import { AppHeader } from "@/components/app-header";
import { AuthSessionProvider } from "@/components/auth/auth-session-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider session={session}>
          <AppStateProvider>
            <RoleProvider>
              <AppHeader />
              <main className="container mx-auto px-4 md:px-6 py-6 md:py-10">
                {children}
              </main>
            </RoleProvider>
          </AppStateProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
